### ISSUE TITLE
Removing "SkyProc" text

### ISSUE THREAD

**Issue by Andoryuuta** [digitalstars/BlueProtocol-Translate#3]
Hello!

I'm the creator of the [original dinput8.dll](https://github.com/SkyProc/translation) / en translation patch.

If it's not too much trouble, could you please hex-edit out the "SkyProc" strings from the .dll you are distributing currently? (e.g. change the `SkyProc Launcher - Done!` messagebox text).

Some people are mistakenly thinking that the modified .dll/patch is affiliated with me, and I'd prefer if they didn't considering the circumstances. 😅 

Thanks!

**Comment by Gnbiggs** [comment]
Hi Andoryuuta,

My question was more on a base of how did you do it, from a learning perspective. I understand there are new creators of the application and DLL file, my query was around how did you reverse engineer the game and build the DLL file? I have tried reaching out via email but have not received any response, so figured, with you still uploading to github, that this would be the best way to communicate. Apologies if there was been some confusion but if you could share knowledge on how skyproc works I would be very interested.

Thanks, Biggs.

**Comment by digitalstars** [comment]
Already deleted
