### ISSUE TITLE
Translater not working since the update of August 16th

### ISSUE THREAD

**Issue by Mejanos** [digitalstars/BlueProtocol-Translate#4]
Hi, 

The translater is not working since the new update. Is there a way to make it work ?

Tanks a lot, 
Mejanos.

**Comment by manh3aven** [comment]
you can delete dinput8.dll and play. but some of the options will not be in English translated.

**Comment by LYTzeng** [comment]
you can join the blue protocol translate discord server to find the current workarounds.

**Comment by digitalstars** [comment]
After the last update, the client patch is broken. To make the game start working, delete dinput8.dll
A new version dinput8.dll may be coming soon. 

The update for the English server patch can be found in Discord

**Comment by JonKookie** [comment]
> After the last update, the client patch is broken. To make the game start working, delete dinput8.dll A new version dinput8.dll may be coming soon.
> 
> The update for the English server patch can be found in Discord

May I know what is the Discord channel for this English patch sever?
